import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787898447679 implements MigrationInterface {
    name = 'InitialSchema1787898447679'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "phone" varchar, "role" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "dateJoined" varchar, "adminRole" varchar, "permissions" varchar, "isApproved" boolean NOT NULL DEFAULT (1), "emailVerified" boolean NOT NULL DEFAULT (0), "emailVerificationToken" varchar, "passwordResetToken" varchar, "passwordResetExpires" varchar, "mfaSecret" varchar, "mfaEnabled" boolean NOT NULL DEFAULT (0), "loginAttempts" integer NOT NULL DEFAULT (0), "lockoutUntil" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE TABLE "providers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar NOT NULL, "avatar" varchar, "title" varchar NOT NULL, "rating" float NOT NULL DEFAULT (5), "reviewCount" integer NOT NULL DEFAULT (0), "experience" integer NOT NULL DEFAULT (0), "available" boolean NOT NULL DEFAULT (1), "verified" boolean NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('active'), "pricePerVisit" integer NOT NULL DEFAULT (0), "distance" varchar, "servicesRaw" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_b0a257f97e76b698c4935b27d7" ON "providers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38e0aae31c55b02a23a6e1af50" ON "providers" ("available") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a657196927a482ede6c5af4e9" ON "providers" ("verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0fc818fbf9f1beca06f05f373" ON "providers" ("status") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, "icon" varchar, "priceFrom" integer NOT NULL DEFAULT (0), "providerCount" integer NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('active'))`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "providerId" varchar, "serviceId" varchar, "patientName" varchar, "patientAvatar" varchar, "providerName" varchar, "providerAvatar" varchar, "service" varchar, "date" varchar NOT NULL, "time" varchar NOT NULL, "location" varchar, "amount" integer NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_13c2e57cb81b44f062ba24df57" ON "appointments" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2428e01f899c4edb909e8798b6" ON "appointments" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f77953c373efb8ab146d98e90c" ON "appointments" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b8e84de5d15269b7f79187992" ON "appointments" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3007a47d97a542e63b3308a69b" ON "appointments" ("status") `);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" varchar PRIMARY KEY NOT NULL, "reporterId" varchar, "reporterName" varchar, "reporterRole" varchar NOT NULL, "subject" varchar NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "priority" varchar NOT NULL DEFAULT ('medium'), "description" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_40cbdbb1a0c58560068efddb80" ON "complaints" ("reporterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_feac32ba8f03b0438df22cb93c" ON "complaints" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_208ad761b4359509cd2f43da87" ON "complaints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_79da475e1369d8165fa6f6d329" ON "complaints" ("priority") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" varchar PRIMARY KEY NOT NULL, "reviewerId" varchar, "providerId" varchar, "serviceId" varchar, "reviewerName" varchar, "providerName" varchar, "service" varchar, "rating" float NOT NULL DEFAULT (5), "comment" text NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('published'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_f9238c3e3739dc40322f577fc4" ON "reviews" ("reviewerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c29faa8169d9741d3a1d51483" ON "reviews" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9563540c43639a0669f68e8ebe" ON "reviews" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_485c9ad56c42479f2bb2b20060" ON "reviews" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2" ON "reviews" ("status") `);
        await queryRunner.query(`CREATE TABLE "emergencies" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "responderId" varchar, "patient" varchar, "responder" varchar, "location" varchar NOT NULL, "phone" varchar NOT NULL, "time" varchar NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_8cfb7416dc7796cb0050cfbf87" ON "emergencies" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3462d9d834cee1bfb0294c0f5" ON "emergencies" ("responderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_726d6e05ba45cbb261ea7dde1c" ON "emergencies" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_a03eff2e5d71918be548aa09b9" ON "emergencies" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d1c1a068c72fc8d63acb440a4" ON "emergencies" ("status") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar, "role" varchar NOT NULL, "x" float NOT NULL, "y" float NOT NULL, "status" varchar NOT NULL DEFAULT ('available'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_78eda52dc27b7ad20350c4a752" ON "locations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8254957861f5dca75bfeef3f15" ON "locations" ("status") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "refreshToken" varchar NOT NULL, "tokenExpires" varchar NOT NULL, "userAgent" varchar, "ipAddress" varchar, "isRevoked" boolean NOT NULL DEFAULT (0), "lastActive" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE TABLE "patient_profiles" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "bloodType" varchar, "allergies" varchar, "medicalHistory" varchar)`);
        await queryRunner.query(`CREATE INDEX "IDX_fc4788002ae2de0a68f6ccf24e" ON "patient_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "provider_profiles" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "specialization" varchar, "bio" varchar, "experienceYears" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE INDEX "IDX_96071d5ba65f9c64f0f2dfdfaf" ON "provider_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "provider_qualifications" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "degree" varchar NOT NULL, "institution" varchar NOT NULL, "graduationYear" integer NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_a26e9c43242268bc7b82fb875e" ON "provider_qualifications" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "provider_licenses" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "licenseNumber" varchar NOT NULL, "issuingAuthority" varchar NOT NULL, "expiryDate" varchar NOT NULL, CONSTRAINT "UQ_7173869a83efd801de4fe279ba6" UNIQUE ("licenseNumber"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e367e21342bf651c27bb002d39" ON "provider_licenses" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "credential_documents" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "docType" varchar NOT NULL, "fileUrl" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'))`);
        await queryRunner.query(`CREATE INDEX "IDX_50b1287e798cf2a7e4278bd5aa" ON "credential_documents" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "verification_reviews" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "reviewerId" varchar NOT NULL, "notes" varchar, "decision" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_3f35b52c22899450cebe93c84a" ON "verification_reviews" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "verification_history" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "status" varchar NOT NULL, "changedBy" varchar NOT NULL, "notes" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_98f415e4dceba5baace43f4a84" ON "verification_history" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "service_categories" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "UQ_7ef2e28b495d09a4eb28997c653" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ef2e28b495d09a4eb28997c65" ON "service_categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "provider_services" ("providerId" varchar NOT NULL, "serviceId" varchar NOT NULL, PRIMARY KEY ("providerId", "serviceId"))`);
        await queryRunner.query(`CREATE TABLE "appointment_status_history" ("id" varchar PRIMARY KEY NOT NULL, "appointmentId" varchar NOT NULL, "status" varchar NOT NULL, "changedBy" varchar NOT NULL, "notes" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_6eb445d53f967e209811b4a0d5" ON "appointment_status_history" ("appointmentId") `);
        await queryRunner.query(`CREATE TABLE "appointment_cancellations" ("id" varchar PRIMARY KEY NOT NULL, "appointmentId" varchar NOT NULL, "reason" varchar NOT NULL, "cancelledBy" varchar NOT NULL, "notes" varchar, CONSTRAINT "UQ_301a0d30740befe8d9b07ef0c5e" UNIQUE ("appointmentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_301a0d30740befe8d9b07ef0c5" ON "appointment_cancellations" ("appointmentId") `);
        await queryRunner.query(`CREATE TABLE "payment_events" ("id" varchar PRIMARY KEY NOT NULL, "paymentId" varchar NOT NULL, "eventType" varchar NOT NULL, "payload" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_c0f8796eab0370f6dc1d8d10db" ON "payment_events" ("paymentId") `);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" varchar PRIMARY KEY NOT NULL, "paymentId" varchar NOT NULL, "amount" integer NOT NULL, "reason" varchar, "status" varchar NOT NULL, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_a276dea330e561499e4a6e1b30" ON "refunds" ("paymentId") `);
        await queryRunner.query(`CREATE TABLE "commission_records" ("id" varchar PRIMARY KEY NOT NULL, "paymentId" varchar NOT NULL, "amount" integer NOT NULL, "ratePercentage" integer NOT NULL, "status" varchar NOT NULL, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_c5d7d4e1a32f32a7cf56889267" ON "commission_records" ("paymentId") `);
        await queryRunner.query(`CREATE TABLE "payouts" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "amount" integer NOT NULL, "status" varchar NOT NULL, "bankAccount" varchar, "transactionReference" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_342fa3891932f5a087dd309d0a" ON "payouts" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL DEFAULT ('direct'), "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("id" varchar PRIMARY KEY NOT NULL, "conversationId" varchar NOT NULL, "userId" varchar NOT NULL, "joinedAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_4453e20858b14ab765a09ad728" ON "conversation_participants" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_18c4ba3b127461649e5f5039db" ON "conversation_participants" ("userId") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" varchar PRIMARY KEY NOT NULL, "conversationId" varchar NOT NULL, "senderId" varchar NOT NULL, "text" varchar NOT NULL, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_e5663ce0c730b2de83445e2fd1" ON "messages" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2db9cf2b3ca111742793f6c37c" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE TABLE "message_attachments" ("id" varchar PRIMARY KEY NOT NULL, "messageId" varchar NOT NULL, "fileUrl" varchar NOT NULL, "fileType" varchar, "fileSize" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b4f24737fcb6b35ffdd4d16e1" ON "message_attachments" ("messageId") `);
        await queryRunner.query(`CREATE TABLE "notification_delivery_attempts" ("id" varchar PRIMARY KEY NOT NULL, "notificationId" varchar NOT NULL, "userId" varchar NOT NULL, "channel" varchar NOT NULL, "status" varchar NOT NULL, "retryCount" integer NOT NULL DEFAULT (0), "errorMessage" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_7386a6f47152f6f0986c4799c8" ON "notification_delivery_attempts" ("notificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d2b2a13d83a5670f81a9241f4" ON "notification_delivery_attempts" ("userId") `);
        await queryRunner.query(`CREATE TABLE "medical_record_access_logs" ("id" varchar PRIMARY KEY NOT NULL, "recordId" varchar NOT NULL, "userId" varchar NOT NULL, "accessType" varchar NOT NULL, "ipAddress" varchar, "userAgent" varchar, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_eed187bcacbefef003486b87db" ON "medical_record_access_logs" ("recordId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9aede362dee4261d78e6f38e15" ON "medical_record_access_logs" ("userId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "actorId" varchar NOT NULL, "action" varchar NOT NULL, "resource" varchar NOT NULL, "timestamp" varchar NOT NULL, "status" varchar NOT NULL, "payload" varchar)`);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_88dcc148d532384790ab874c3d" ON "audit_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "file_metadata" ("id" varchar PRIMARY KEY NOT NULL, "fileName" varchar NOT NULL, "mimeType" varchar NOT NULL, "fileSize" integer NOT NULL, "url" varchar NOT NULL, "uploaderId" varchar NOT NULL, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_949fc80b4c5fe26466ec7db6b1" ON "file_metadata" ("uploaderId") `);
        await queryRunner.query(`CREATE TABLE "emergency_responders" ("id" varchar PRIMARY KEY NOT NULL, "emergencyId" varchar NOT NULL, "providerId" varchar NOT NULL, "dispatchedAt" varchar NOT NULL, "arrivedAt" varchar)`);
        await queryRunner.query(`CREATE INDEX "IDX_11c03bc64fcacd1a4df3c97bea" ON "emergency_responders" ("emergencyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c02e7b4210f3b8db4b77d6db10" ON "emergency_responders" ("providerId") `);
        await queryRunner.query(`CREATE TABLE "emergency_escalation_history" ("id" varchar PRIMARY KEY NOT NULL, "emergencyId" varchar NOT NULL, "level" varchar NOT NULL, "reason" varchar, "escalatedBy" varchar NOT NULL, "createdAt" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_d2f08832f73ca51f283818d009" ON "emergency_escalation_history" ("emergencyId") `);
        await queryRunner.query(`CREATE TABLE "location_history" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "x" integer NOT NULL, "y" integer NOT NULL, "timestamp" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_2c7ae21d39ee62de77c45b6945" ON "location_history" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_262c67ffe7c6f1ec176c11ad1a" ON "location_history" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "provider_time_off" ("id" varchar PRIMARY KEY NOT NULL, "providerId" varchar NOT NULL, "startDate" varchar NOT NULL, "endDate" varchar NOT NULL, "reason" varchar)`);
        await queryRunner.query(`CREATE INDEX "IDX_6f2a4820ab5d6a7072336a3fa6" ON "provider_time_off" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f6d520844e10b6f8e2c1a0fd5" ON "provider_time_off" ("startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_351e8161ca395d19572102b345" ON "provider_time_off" ("endDate") `);
        await queryRunner.query(`DROP INDEX "IDX_b0a257f97e76b698c4935b27d7"`);
        await queryRunner.query(`DROP INDEX "IDX_38e0aae31c55b02a23a6e1af50"`);
        await queryRunner.query(`DROP INDEX "IDX_8a657196927a482ede6c5af4e9"`);
        await queryRunner.query(`DROP INDEX "IDX_e0fc818fbf9f1beca06f05f373"`);
        await queryRunner.query(`CREATE TABLE "temporary_providers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar NOT NULL, "avatar" varchar, "title" varchar NOT NULL, "rating" float NOT NULL DEFAULT (5), "reviewCount" integer NOT NULL DEFAULT (0), "experience" integer NOT NULL DEFAULT (0), "available" boolean NOT NULL DEFAULT (1), "verified" boolean NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('active'), "pricePerVisit" integer NOT NULL DEFAULT (0), "distance" varchar, "servicesRaw" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL, CONSTRAINT "FK_b0a257f97e76b698c4935b27d7d" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_providers"("id", "userId", "name", "avatar", "title", "rating", "reviewCount", "experience", "available", "verified", "status", "pricePerVisit", "distance", "servicesRaw", "createdAt", "updatedAt", "deletedAt", "version") SELECT "id", "userId", "name", "avatar", "title", "rating", "reviewCount", "experience", "available", "verified", "status", "pricePerVisit", "distance", "servicesRaw", "createdAt", "updatedAt", "deletedAt", "version" FROM "providers"`);
        await queryRunner.query(`DROP TABLE "providers"`);
        await queryRunner.query(`ALTER TABLE "temporary_providers" RENAME TO "providers"`);
        await queryRunner.query(`CREATE INDEX "IDX_b0a257f97e76b698c4935b27d7" ON "providers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38e0aae31c55b02a23a6e1af50" ON "providers" ("available") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a657196927a482ede6c5af4e9" ON "providers" ("verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0fc818fbf9f1beca06f05f373" ON "providers" ("status") `);
        await queryRunner.query(`DROP INDEX "IDX_13c2e57cb81b44f062ba24df57"`);
        await queryRunner.query(`DROP INDEX "IDX_2428e01f899c4edb909e8798b6"`);
        await queryRunner.query(`DROP INDEX "IDX_f77953c373efb8ab146d98e90c"`);
        await queryRunner.query(`DROP INDEX "IDX_6b8e84de5d15269b7f79187992"`);
        await queryRunner.query(`DROP INDEX "IDX_3007a47d97a542e63b3308a69b"`);
        await queryRunner.query(`CREATE TABLE "temporary_appointments" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "providerId" varchar, "serviceId" varchar, "patientName" varchar, "patientAvatar" varchar, "providerName" varchar, "providerAvatar" varchar, "service" varchar, "date" varchar NOT NULL, "time" varchar NOT NULL, "location" varchar, "amount" integer NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL, CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_2428e01f899c4edb909e8798b63" FOREIGN KEY ("providerId") REFERENCES "providers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f77953c373efb8ab146d98e90c3" FOREIGN KEY ("serviceId") REFERENCES "services" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_appointments"("id", "patientId", "providerId", "serviceId", "patientName", "patientAvatar", "providerName", "providerAvatar", "service", "date", "time", "location", "amount", "status", "createdAt", "updatedAt", "deletedAt", "version") SELECT "id", "patientId", "providerId", "serviceId", "patientName", "patientAvatar", "providerName", "providerAvatar", "service", "date", "time", "location", "amount", "status", "createdAt", "updatedAt", "deletedAt", "version" FROM "appointments"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`ALTER TABLE "temporary_appointments" RENAME TO "appointments"`);
        await queryRunner.query(`CREATE INDEX "IDX_13c2e57cb81b44f062ba24df57" ON "appointments" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2428e01f899c4edb909e8798b6" ON "appointments" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f77953c373efb8ab146d98e90c" ON "appointments" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b8e84de5d15269b7f79187992" ON "appointments" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3007a47d97a542e63b3308a69b" ON "appointments" ("status") `);
        await queryRunner.query(`DROP INDEX "IDX_40cbdbb1a0c58560068efddb80"`);
        await queryRunner.query(`DROP INDEX "IDX_feac32ba8f03b0438df22cb93c"`);
        await queryRunner.query(`DROP INDEX "IDX_208ad761b4359509cd2f43da87"`);
        await queryRunner.query(`DROP INDEX "IDX_79da475e1369d8165fa6f6d329"`);
        await queryRunner.query(`CREATE TABLE "temporary_complaints" ("id" varchar PRIMARY KEY NOT NULL, "reporterId" varchar, "reporterName" varchar, "reporterRole" varchar NOT NULL, "subject" varchar NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "priority" varchar NOT NULL DEFAULT ('medium'), "description" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_40cbdbb1a0c58560068efddb803" FOREIGN KEY ("reporterId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_complaints"("id", "reporterId", "reporterName", "reporterRole", "subject", "date", "status", "priority", "description", "createdAt", "updatedAt", "deletedAt") SELECT "id", "reporterId", "reporterName", "reporterRole", "subject", "date", "status", "priority", "description", "createdAt", "updatedAt", "deletedAt" FROM "complaints"`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`ALTER TABLE "temporary_complaints" RENAME TO "complaints"`);
        await queryRunner.query(`CREATE INDEX "IDX_40cbdbb1a0c58560068efddb80" ON "complaints" ("reporterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_feac32ba8f03b0438df22cb93c" ON "complaints" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_208ad761b4359509cd2f43da87" ON "complaints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_79da475e1369d8165fa6f6d329" ON "complaints" ("priority") `);
        await queryRunner.query(`DROP INDEX "IDX_f9238c3e3739dc40322f577fc4"`);
        await queryRunner.query(`DROP INDEX "IDX_4c29faa8169d9741d3a1d51483"`);
        await queryRunner.query(`DROP INDEX "IDX_9563540c43639a0669f68e8ebe"`);
        await queryRunner.query(`DROP INDEX "IDX_485c9ad56c42479f2bb2b20060"`);
        await queryRunner.query(`DROP INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2"`);
        await queryRunner.query(`CREATE TABLE "temporary_reviews" ("id" varchar PRIMARY KEY NOT NULL, "reviewerId" varchar, "providerId" varchar, "serviceId" varchar, "reviewerName" varchar, "providerName" varchar, "service" varchar, "rating" float NOT NULL DEFAULT (5), "comment" text NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('published'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_f9238c3e3739dc40322f577fc46" FOREIGN KEY ("reviewerId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_4c29faa8169d9741d3a1d514830" FOREIGN KEY ("providerId") REFERENCES "providers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_9563540c43639a0669f68e8ebe3" FOREIGN KEY ("serviceId") REFERENCES "services" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reviews"("id", "reviewerId", "providerId", "serviceId", "reviewerName", "providerName", "service", "rating", "comment", "date", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "reviewerId", "providerId", "serviceId", "reviewerName", "providerName", "service", "rating", "comment", "date", "status", "createdAt", "updatedAt", "deletedAt" FROM "reviews"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`ALTER TABLE "temporary_reviews" RENAME TO "reviews"`);
        await queryRunner.query(`CREATE INDEX "IDX_f9238c3e3739dc40322f577fc4" ON "reviews" ("reviewerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c29faa8169d9741d3a1d51483" ON "reviews" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9563540c43639a0669f68e8ebe" ON "reviews" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_485c9ad56c42479f2bb2b20060" ON "reviews" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2" ON "reviews" ("status") `);
        await queryRunner.query(`DROP INDEX "IDX_8cfb7416dc7796cb0050cfbf87"`);
        await queryRunner.query(`DROP INDEX "IDX_d3462d9d834cee1bfb0294c0f5"`);
        await queryRunner.query(`DROP INDEX "IDX_726d6e05ba45cbb261ea7dde1c"`);
        await queryRunner.query(`DROP INDEX "IDX_a03eff2e5d71918be548aa09b9"`);
        await queryRunner.query(`DROP INDEX "IDX_2d1c1a068c72fc8d63acb440a4"`);
        await queryRunner.query(`CREATE TABLE "temporary_emergencies" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "responderId" varchar, "patient" varchar, "responder" varchar, "location" varchar NOT NULL, "phone" varchar NOT NULL, "time" varchar NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_8cfb7416dc7796cb0050cfbf87c" FOREIGN KEY ("patientId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_d3462d9d834cee1bfb0294c0f5c" FOREIGN KEY ("responderId") REFERENCES "providers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_emergencies"("id", "patientId", "responderId", "patient", "responder", "location", "phone", "time", "type", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "patientId", "responderId", "patient", "responder", "location", "phone", "time", "type", "status", "createdAt", "updatedAt", "deletedAt" FROM "emergencies"`);
        await queryRunner.query(`DROP TABLE "emergencies"`);
        await queryRunner.query(`ALTER TABLE "temporary_emergencies" RENAME TO "emergencies"`);
        await queryRunner.query(`CREATE INDEX "IDX_8cfb7416dc7796cb0050cfbf87" ON "emergencies" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3462d9d834cee1bfb0294c0f5" ON "emergencies" ("responderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_726d6e05ba45cbb261ea7dde1c" ON "emergencies" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_a03eff2e5d71918be548aa09b9" ON "emergencies" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d1c1a068c72fc8d63acb440a4" ON "emergencies" ("status") `);
        await queryRunner.query(`DROP INDEX "IDX_78eda52dc27b7ad20350c4a752"`);
        await queryRunner.query(`DROP INDEX "IDX_8254957861f5dca75bfeef3f15"`);
        await queryRunner.query(`CREATE TABLE "temporary_locations" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar, "role" varchar NOT NULL, "x" float NOT NULL, "y" float NOT NULL, "status" varchar NOT NULL DEFAULT ('available'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_78eda52dc27b7ad20350c4a752d" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_locations"("id", "userId", "name", "role", "x", "y", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "userId", "name", "role", "x", "y", "status", "createdAt", "updatedAt", "deletedAt" FROM "locations"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`ALTER TABLE "temporary_locations" RENAME TO "locations"`);
        await queryRunner.query(`CREATE INDEX "IDX_78eda52dc27b7ad20350c4a752" ON "locations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8254957861f5dca75bfeef3f15" ON "locations" ("status") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_8254957861f5dca75bfeef3f15"`);
        await queryRunner.query(`DROP INDEX "IDX_78eda52dc27b7ad20350c4a752"`);
        await queryRunner.query(`ALTER TABLE "locations" RENAME TO "temporary_locations"`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar, "role" varchar NOT NULL, "x" float NOT NULL, "y" float NOT NULL, "status" varchar NOT NULL DEFAULT ('available'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "locations"("id", "userId", "name", "role", "x", "y", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "userId", "name", "role", "x", "y", "status", "createdAt", "updatedAt", "deletedAt" FROM "temporary_locations"`);
        await queryRunner.query(`DROP TABLE "temporary_locations"`);
        await queryRunner.query(`CREATE INDEX "IDX_8254957861f5dca75bfeef3f15" ON "locations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_78eda52dc27b7ad20350c4a752" ON "locations" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_2d1c1a068c72fc8d63acb440a4"`);
        await queryRunner.query(`DROP INDEX "IDX_a03eff2e5d71918be548aa09b9"`);
        await queryRunner.query(`DROP INDEX "IDX_726d6e05ba45cbb261ea7dde1c"`);
        await queryRunner.query(`DROP INDEX "IDX_d3462d9d834cee1bfb0294c0f5"`);
        await queryRunner.query(`DROP INDEX "IDX_8cfb7416dc7796cb0050cfbf87"`);
        await queryRunner.query(`ALTER TABLE "emergencies" RENAME TO "temporary_emergencies"`);
        await queryRunner.query(`CREATE TABLE "emergencies" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "responderId" varchar, "patient" varchar, "responder" varchar, "location" varchar NOT NULL, "phone" varchar NOT NULL, "time" varchar NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "emergencies"("id", "patientId", "responderId", "patient", "responder", "location", "phone", "time", "type", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "patientId", "responderId", "patient", "responder", "location", "phone", "time", "type", "status", "createdAt", "updatedAt", "deletedAt" FROM "temporary_emergencies"`);
        await queryRunner.query(`DROP TABLE "temporary_emergencies"`);
        await queryRunner.query(`CREATE INDEX "IDX_2d1c1a068c72fc8d63acb440a4" ON "emergencies" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a03eff2e5d71918be548aa09b9" ON "emergencies" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_726d6e05ba45cbb261ea7dde1c" ON "emergencies" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3462d9d834cee1bfb0294c0f5" ON "emergencies" ("responderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cfb7416dc7796cb0050cfbf87" ON "emergencies" ("patientId") `);
        await queryRunner.query(`DROP INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2"`);
        await queryRunner.query(`DROP INDEX "IDX_485c9ad56c42479f2bb2b20060"`);
        await queryRunner.query(`DROP INDEX "IDX_9563540c43639a0669f68e8ebe"`);
        await queryRunner.query(`DROP INDEX "IDX_4c29faa8169d9741d3a1d51483"`);
        await queryRunner.query(`DROP INDEX "IDX_f9238c3e3739dc40322f577fc4"`);
        await queryRunner.query(`ALTER TABLE "reviews" RENAME TO "temporary_reviews"`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" varchar PRIMARY KEY NOT NULL, "reviewerId" varchar, "providerId" varchar, "serviceId" varchar, "reviewerName" varchar, "providerName" varchar, "service" varchar, "rating" float NOT NULL DEFAULT (5), "comment" text NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('published'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "reviews"("id", "reviewerId", "providerId", "serviceId", "reviewerName", "providerName", "service", "rating", "comment", "date", "status", "createdAt", "updatedAt", "deletedAt") SELECT "id", "reviewerId", "providerId", "serviceId", "reviewerName", "providerName", "service", "rating", "comment", "date", "status", "createdAt", "updatedAt", "deletedAt" FROM "temporary_reviews"`);
        await queryRunner.query(`DROP TABLE "temporary_reviews"`);
        await queryRunner.query(`CREATE INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2" ON "reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_485c9ad56c42479f2bb2b20060" ON "reviews" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9563540c43639a0669f68e8ebe" ON "reviews" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c29faa8169d9741d3a1d51483" ON "reviews" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9238c3e3739dc40322f577fc4" ON "reviews" ("reviewerId") `);
        await queryRunner.query(`DROP INDEX "IDX_79da475e1369d8165fa6f6d329"`);
        await queryRunner.query(`DROP INDEX "IDX_208ad761b4359509cd2f43da87"`);
        await queryRunner.query(`DROP INDEX "IDX_feac32ba8f03b0438df22cb93c"`);
        await queryRunner.query(`DROP INDEX "IDX_40cbdbb1a0c58560068efddb80"`);
        await queryRunner.query(`ALTER TABLE "complaints" RENAME TO "temporary_complaints"`);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" varchar PRIMARY KEY NOT NULL, "reporterId" varchar, "reporterName" varchar, "reporterRole" varchar NOT NULL, "subject" varchar NOT NULL, "date" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "priority" varchar NOT NULL DEFAULT ('medium'), "description" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "complaints"("id", "reporterId", "reporterName", "reporterRole", "subject", "date", "status", "priority", "description", "createdAt", "updatedAt", "deletedAt") SELECT "id", "reporterId", "reporterName", "reporterRole", "subject", "date", "status", "priority", "description", "createdAt", "updatedAt", "deletedAt" FROM "temporary_complaints"`);
        await queryRunner.query(`DROP TABLE "temporary_complaints"`);
        await queryRunner.query(`CREATE INDEX "IDX_79da475e1369d8165fa6f6d329" ON "complaints" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_208ad761b4359509cd2f43da87" ON "complaints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_feac32ba8f03b0438df22cb93c" ON "complaints" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_40cbdbb1a0c58560068efddb80" ON "complaints" ("reporterId") `);
        await queryRunner.query(`DROP INDEX "IDX_3007a47d97a542e63b3308a69b"`);
        await queryRunner.query(`DROP INDEX "IDX_6b8e84de5d15269b7f79187992"`);
        await queryRunner.query(`DROP INDEX "IDX_f77953c373efb8ab146d98e90c"`);
        await queryRunner.query(`DROP INDEX "IDX_2428e01f899c4edb909e8798b6"`);
        await queryRunner.query(`DROP INDEX "IDX_13c2e57cb81b44f062ba24df57"`);
        await queryRunner.query(`ALTER TABLE "appointments" RENAME TO "temporary_appointments"`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" varchar PRIMARY KEY NOT NULL, "patientId" varchar, "providerId" varchar, "serviceId" varchar, "patientName" varchar, "patientAvatar" varchar, "providerName" varchar, "providerAvatar" varchar, "service" varchar, "date" varchar NOT NULL, "time" varchar NOT NULL, "location" varchar, "amount" integer NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "appointments"("id", "patientId", "providerId", "serviceId", "patientName", "patientAvatar", "providerName", "providerAvatar", "service", "date", "time", "location", "amount", "status", "createdAt", "updatedAt", "deletedAt", "version") SELECT "id", "patientId", "providerId", "serviceId", "patientName", "patientAvatar", "providerName", "providerAvatar", "service", "date", "time", "location", "amount", "status", "createdAt", "updatedAt", "deletedAt", "version" FROM "temporary_appointments"`);
        await queryRunner.query(`DROP TABLE "temporary_appointments"`);
        await queryRunner.query(`CREATE INDEX "IDX_3007a47d97a542e63b3308a69b" ON "appointments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b8e84de5d15269b7f79187992" ON "appointments" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f77953c373efb8ab146d98e90c" ON "appointments" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2428e01f899c4edb909e8798b6" ON "appointments" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c2e57cb81b44f062ba24df57" ON "appointments" ("patientId") `);
        await queryRunner.query(`DROP INDEX "IDX_e0fc818fbf9f1beca06f05f373"`);
        await queryRunner.query(`DROP INDEX "IDX_8a657196927a482ede6c5af4e9"`);
        await queryRunner.query(`DROP INDEX "IDX_38e0aae31c55b02a23a6e1af50"`);
        await queryRunner.query(`DROP INDEX "IDX_b0a257f97e76b698c4935b27d7"`);
        await queryRunner.query(`ALTER TABLE "providers" RENAME TO "temporary_providers"`);
        await queryRunner.query(`CREATE TABLE "providers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar, "name" varchar NOT NULL, "avatar" varchar, "title" varchar NOT NULL, "rating" float NOT NULL DEFAULT (5), "reviewCount" integer NOT NULL DEFAULT (0), "experience" integer NOT NULL DEFAULT (0), "available" boolean NOT NULL DEFAULT (1), "verified" boolean NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('active'), "pricePerVisit" integer NOT NULL DEFAULT (0), "distance" varchar, "servicesRaw" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "version" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "providers"("id", "userId", "name", "avatar", "title", "rating", "reviewCount", "experience", "available", "verified", "status", "pricePerVisit", "distance", "servicesRaw", "createdAt", "updatedAt", "deletedAt", "version") SELECT "id", "userId", "name", "avatar", "title", "rating", "reviewCount", "experience", "available", "verified", "status", "pricePerVisit", "distance", "servicesRaw", "createdAt", "updatedAt", "deletedAt", "version" FROM "temporary_providers"`);
        await queryRunner.query(`DROP TABLE "temporary_providers"`);
        await queryRunner.query(`CREATE INDEX "IDX_e0fc818fbf9f1beca06f05f373" ON "providers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a657196927a482ede6c5af4e9" ON "providers" ("verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_38e0aae31c55b02a23a6e1af50" ON "providers" ("available") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0a257f97e76b698c4935b27d7" ON "providers" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_351e8161ca395d19572102b345"`);
        await queryRunner.query(`DROP INDEX "IDX_8f6d520844e10b6f8e2c1a0fd5"`);
        await queryRunner.query(`DROP INDEX "IDX_6f2a4820ab5d6a7072336a3fa6"`);
        await queryRunner.query(`DROP TABLE "provider_time_off"`);
        await queryRunner.query(`DROP INDEX "IDX_262c67ffe7c6f1ec176c11ad1a"`);
        await queryRunner.query(`DROP INDEX "IDX_2c7ae21d39ee62de77c45b6945"`);
        await queryRunner.query(`DROP TABLE "location_history"`);
        await queryRunner.query(`DROP INDEX "IDX_d2f08832f73ca51f283818d009"`);
        await queryRunner.query(`DROP TABLE "emergency_escalation_history"`);
        await queryRunner.query(`DROP INDEX "IDX_c02e7b4210f3b8db4b77d6db10"`);
        await queryRunner.query(`DROP INDEX "IDX_11c03bc64fcacd1a4df3c97bea"`);
        await queryRunner.query(`DROP TABLE "emergency_responders"`);
        await queryRunner.query(`DROP INDEX "IDX_949fc80b4c5fe26466ec7db6b1"`);
        await queryRunner.query(`DROP TABLE "file_metadata"`);
        await queryRunner.query(`DROP INDEX "IDX_88dcc148d532384790ab874c3d"`);
        await queryRunner.query(`DROP INDEX "IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_9aede362dee4261d78e6f38e15"`);
        await queryRunner.query(`DROP INDEX "IDX_eed187bcacbefef003486b87db"`);
        await queryRunner.query(`DROP TABLE "medical_record_access_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_6d2b2a13d83a5670f81a9241f4"`);
        await queryRunner.query(`DROP INDEX "IDX_7386a6f47152f6f0986c4799c8"`);
        await queryRunner.query(`DROP TABLE "notification_delivery_attempts"`);
        await queryRunner.query(`DROP INDEX "IDX_5b4f24737fcb6b35ffdd4d16e1"`);
        await queryRunner.query(`DROP TABLE "message_attachments"`);
        await queryRunner.query(`DROP INDEX "IDX_2db9cf2b3ca111742793f6c37c"`);
        await queryRunner.query(`DROP INDEX "IDX_e5663ce0c730b2de83445e2fd1"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "IDX_18c4ba3b127461649e5f5039db"`);
        await queryRunner.query(`DROP INDEX "IDX_4453e20858b14ab765a09ad728"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "IDX_342fa3891932f5a087dd309d0a"`);
        await queryRunner.query(`DROP TABLE "payouts"`);
        await queryRunner.query(`DROP INDEX "IDX_c5d7d4e1a32f32a7cf56889267"`);
        await queryRunner.query(`DROP TABLE "commission_records"`);
        await queryRunner.query(`DROP INDEX "IDX_a276dea330e561499e4a6e1b30"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP INDEX "IDX_c0f8796eab0370f6dc1d8d10db"`);
        await queryRunner.query(`DROP TABLE "payment_events"`);
        await queryRunner.query(`DROP INDEX "IDX_301a0d30740befe8d9b07ef0c5"`);
        await queryRunner.query(`DROP TABLE "appointment_cancellations"`);
        await queryRunner.query(`DROP INDEX "IDX_6eb445d53f967e209811b4a0d5"`);
        await queryRunner.query(`DROP TABLE "appointment_status_history"`);
        await queryRunner.query(`DROP TABLE "provider_services"`);
        await queryRunner.query(`DROP INDEX "IDX_7ef2e28b495d09a4eb28997c65"`);
        await queryRunner.query(`DROP TABLE "service_categories"`);
        await queryRunner.query(`DROP INDEX "IDX_98f415e4dceba5baace43f4a84"`);
        await queryRunner.query(`DROP TABLE "verification_history"`);
        await queryRunner.query(`DROP INDEX "IDX_3f35b52c22899450cebe93c84a"`);
        await queryRunner.query(`DROP TABLE "verification_reviews"`);
        await queryRunner.query(`DROP INDEX "IDX_50b1287e798cf2a7e4278bd5aa"`);
        await queryRunner.query(`DROP TABLE "credential_documents"`);
        await queryRunner.query(`DROP INDEX "IDX_e367e21342bf651c27bb002d39"`);
        await queryRunner.query(`DROP TABLE "provider_licenses"`);
        await queryRunner.query(`DROP INDEX "IDX_a26e9c43242268bc7b82fb875e"`);
        await queryRunner.query(`DROP TABLE "provider_qualifications"`);
        await queryRunner.query(`DROP INDEX "IDX_96071d5ba65f9c64f0f2dfdfaf"`);
        await queryRunner.query(`DROP TABLE "provider_profiles"`);
        await queryRunner.query(`DROP INDEX "IDX_fc4788002ae2de0a68f6ccf24e"`);
        await queryRunner.query(`DROP TABLE "patient_profiles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_8254957861f5dca75bfeef3f15"`);
        await queryRunner.query(`DROP INDEX "IDX_78eda52dc27b7ad20350c4a752"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "IDX_2d1c1a068c72fc8d63acb440a4"`);
        await queryRunner.query(`DROP INDEX "IDX_a03eff2e5d71918be548aa09b9"`);
        await queryRunner.query(`DROP INDEX "IDX_726d6e05ba45cbb261ea7dde1c"`);
        await queryRunner.query(`DROP INDEX "IDX_d3462d9d834cee1bfb0294c0f5"`);
        await queryRunner.query(`DROP INDEX "IDX_8cfb7416dc7796cb0050cfbf87"`);
        await queryRunner.query(`DROP TABLE "emergencies"`);
        await queryRunner.query(`DROP INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2"`);
        await queryRunner.query(`DROP INDEX "IDX_485c9ad56c42479f2bb2b20060"`);
        await queryRunner.query(`DROP INDEX "IDX_9563540c43639a0669f68e8ebe"`);
        await queryRunner.query(`DROP INDEX "IDX_4c29faa8169d9741d3a1d51483"`);
        await queryRunner.query(`DROP INDEX "IDX_f9238c3e3739dc40322f577fc4"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "IDX_79da475e1369d8165fa6f6d329"`);
        await queryRunner.query(`DROP INDEX "IDX_208ad761b4359509cd2f43da87"`);
        await queryRunner.query(`DROP INDEX "IDX_feac32ba8f03b0438df22cb93c"`);
        await queryRunner.query(`DROP INDEX "IDX_40cbdbb1a0c58560068efddb80"`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`DROP INDEX "IDX_3007a47d97a542e63b3308a69b"`);
        await queryRunner.query(`DROP INDEX "IDX_6b8e84de5d15269b7f79187992"`);
        await queryRunner.query(`DROP INDEX "IDX_f77953c373efb8ab146d98e90c"`);
        await queryRunner.query(`DROP INDEX "IDX_2428e01f899c4edb909e8798b6"`);
        await queryRunner.query(`DROP INDEX "IDX_13c2e57cb81b44f062ba24df57"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "IDX_e0fc818fbf9f1beca06f05f373"`);
        await queryRunner.query(`DROP INDEX "IDX_8a657196927a482ede6c5af4e9"`);
        await queryRunner.query(`DROP INDEX "IDX_38e0aae31c55b02a23a6e1af50"`);
        await queryRunner.query(`DROP INDEX "IDX_b0a257f97e76b698c4935b27d7"`);
        await queryRunner.query(`DROP TABLE "providers"`);
        await queryRunner.query(`DROP INDEX "IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
